version: '3'
services:
  app:
    env_file:
      - .env
    container_name: time-tracker
    restart: always
    image: 5track/time-tracker
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    env_file:
      - .env
  nginx:
    container_name: nginx
    restart: always
    build:
      context: nginx/.
    ports:
      - '80:80'
      - '443:443'

volumes:
  pgdata:
